name: student_grade_calculator
description: A Student Grade Calculator with Excel integration in Dart
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  excel: ^4.0.6
  path: ^1.9.0

dev_dependencies:
  flutter_lints: ^3.0.0
